[package]
name = "nibble-8-gui"
version = "0.1.0"
edition = "2024"

[dependencies]
nibble-8-core = { path = "../nibble-8-core/" }
[dependencies.sdl2]
version = "0.38"
default-features = false
features = ["ttf"]
